// Mirrors the site's Google Fonts locally.
//
// Re-run after changing which families or weights the site uses:
//     node scripts/fetch-fonts.mjs
//
// Downloads the woff2 files Google would serve and writes src/styles/fonts.css
// with the same @font-face rules, unicode-ranges and font-display, pointed at
// /fonts/ instead. Because global.css is inlined into every page, the browser
// then discovers the font files while parsing the HTML, instead of after a
// blocking round trip to a third-party stylesheet.
//
// The request carries a Chrome user-agent because Google varies the CSS by
// user-agent, and only a modern one yields woff2 rather than legacy formats.
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const CHROME_UA =
	'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36';

// Keep in sync with the families the stylesheets actually reference.
const FAMILIES = [
	{
		name: 'inter-dmsans',
		url: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=DM+Sans:wght@300&display=swap',
	},
];

// Google's CSS declares seven unicode subsets per family. A browser only
// downloads the ones it needs, so the extra files cost nothing to serve — but
// the @font-face rules themselves are inlined into every page by
// build.inlineStylesheets, where 37 rules added 9 KB to every HTML document and
// measurably delayed LCP. The site's content is entirely Latin, so only these
// subsets are kept. Re-check with a scan of src/ before adding content in
// another script.
const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);

const FONT_DIR = path.resolve(process.cwd(), 'public/fonts');
const CSS_OUT = path.resolve(process.cwd(), 'src/styles/fonts.css');

// Google's CSS labels each @font-face with a `/* subset */` comment above it.
function keepOnlyWantedSubsets(css) {
	const blocks = css.split(/(?=\/\* [a-z-]+ \*\/)/);
	return blocks
		.filter((b) => {
			const label = /^\/\* ([a-z-]+) \*\//.exec(b.trim())?.[1];
			return label ? KEEP_SUBSETS.has(label) : true;
		})
		.join('');
}

await mkdir(FONT_DIR, { recursive: true });

// Google's URLs look like .../s/inter/v20/<hash>.woff2 — the hash alone is not
// descriptive, so name files by family and a short hash for stability.
function localName(url) {
	const m = /\/s\/([^/]+)\/[^/]+\/([^.]+)\.woff2/.exec(url);
	const family = m?.[1] ?? 'font';
	const hash = (m?.[2] ?? String(Math.random())).slice(-12);
	return `${family}-${hash}.woff2`;
}

const chunks = [
	'/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.',
	' * Self-hosted copies of the Google Fonts the site uses. Same files, same',
	' * unicode-ranges, same font-display, served same-origin so they are',
	' * discovered during HTML parse rather than after a blocking third-party',
	' * stylesheet request. */',
	'',
];

let downloaded = 0;
let bytes = 0;

for (const family of FAMILIES) {
	const res = await fetch(family.url, { headers: { 'user-agent': CHROME_UA } });
	if (!res.ok) throw new Error(`CSS fetch failed (${res.status}): ${family.url}`);
	let css = keepOnlyWantedSubsets(await res.text());

	const urls = [...new Set([...css.matchAll(/url\((https:\/\/fonts\.gstatic\.com[^)]+)\)/g)].map((m) => m[1]))];
	for (const url of urls) {
		const name = localName(url);
		const fr = await fetch(url, { headers: { 'user-agent': CHROME_UA } });
		if (!fr.ok) throw new Error(`Font fetch failed (${fr.status}): ${url}`);
		const buf = Buffer.from(await fr.arrayBuffer());
		await writeFile(path.join(FONT_DIR, name), buf);
		css = css.split(url).join(`/fonts/${name}`);
		downloaded++;
		bytes += buf.length;
	}
	chunks.push(css.trim(), '');
}

await writeFile(CSS_OUT, `${chunks.join('\n')}\n`);

console.log(`${downloaded} font files -> public/fonts/ (${(bytes / 1024).toFixed(0)} KB total)`);
console.log(`stylesheet -> ${path.relative(process.cwd(), CSS_OUT)}`);
